version: "3.8"

services:
  dotnet_app:
    container_name: dotnet_service
    image: dotnet8_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    user: "root"
